### ISSUE TITLE
Switch to an arena allocator

### ISSUE THREAD

**Issue by ngoldbaum** [numpy/numpy-user-dtypes#76]
Arrow's string arrays use arrow's [variable-sized binary layout](https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-layout), which stores the string data in a single contiguous buffer per array along with a strided array of integer offsets. This is a really nice design because you only need one heap allocation per array and the string data are contiguous in memory so it's much easier to write fast ufuncs and exploit SIMD. The down side is that string arrays need to either be immutable or there can be pathological cases where enlarging a single array element leads to reallocating the storage for an entire array. I don't think it would be a big downside for many real-world use cases for string arrays to force people to copy into a new array if they need to mutate elements, but it would be a wart in NumPy's API where one data type has restrictions that others don't.

Numpy doesn't have a concept of per-array heap storage outside the array buffer, however even if we added facilities for that, the dtype API doesn't allow access to the array object, so we would also need to add a pointer to the per-array storage to the ufunc loops in the dtype API as well. I think a more straightforward approach would be to let the per-array storage buffer live on the descriptor instance and ensure that each array has a unique descriptor object.

A first step towards figuring out how hard it would be to have unique descriptors per array would be to add a flag to the dtype that indicates the dtype is associated with an array. When we set this flag at array creation time, if the flag is already set, we raise an error. I think running the strigdtype tests with this flag turned on would probably catch most of the places in numpy or the dtype implementation that would need to be updated. Once we're confident a per-array descriptor is possible, we get per-array buffer storage for free, and I think it would be relatively straightfoward to switch to an arrow-like in-memory representation.

**Comment by seberg** [comment]
I don't expect it's super complicated.  All array creation goes through a single function, we only need a hook that gets called whenever an array is _not_ a view into existing data ("owns the data"), in some weird calls that might not work, but that would be some wonky extension code and small API additions can fix that when it comes up.

(to some degree we already do things like that chaging "S0" to "S1" _ugg_ and moving subarray dimensions into the array.)

**Comment by seberg** [comment]
Right, we also have the casting buffers in ufunc code which do get cleared many times (although we currently know that if we clear we clear all memory associated with a dtype!).

So we know where we can put the buffer.  I wonder if we could actually realloc or use a chunked scheme to grow the owning buffer during the operation  (when there is no way to figure out the length ahead of time).  But even that may be hard in practice since a scheme of "allocate empty array and fill it" becomes tricky and.

We can in NumPy currently guarantee that a call on a fresh array can be done in a single strided manner, so if we have a `finalize()` hook that we call in places where it is needed it could actually decide to do a multi-pass call by itself.
You could even do this as a user method like `arr.dtype.freeze()`, although the dtype needs to know the owning array for that (not a problem) and then it would be very weird if you call it from a view.

---

I do wonder a bit how much can we achieve without this?  Some operations in arrow may work directly on the contiguous buffer and the offsets are only really an index when you need that index...

But besides that, another thing it gives you is cache locality, and I wonder if we can achieve that by using an arena/heap allocation scheme?
Currently, the code uses `malloc` which really tends to not be great at many small allocations, although I am not sure if it gives terrible cache locality, I would be surprised if it isn't a real performance hit.  (A quick try would be to use `PyMem_MALLOC/PyMem_FREE` but require the GIL, or `LD_PRELOAD=/path/to/libmimalloc.so` if you have that.)

Maybe @mattip knows if that is nonsense or not (or knows who to ask).  `mimalloc` can only allocate in the creating thread for a heap, but I suspect `jemalloc` can do this.
Asking because someone (maybe graalpython) in the HPy discussion had a memory ownership tied where container elements are tied to the container/owner, which sounds like that.

(A question here may be, if a per array/dtype arena is even useful compared to just a global arena for all string arrays, because fragmentation may be small enough that it doesn't matter too much in pratice.)

It sounds like these allocators try to achieve some memory locality, although if what we want is to operate on the contiguous buffer directly we have lost out: We still need a way to create that "frozenstring" representation.

**Comment by ngoldbaum** [comment]
I think I'm going to stop actively implementing this for now until we have a bigger community discussion around the NEP about what we want. I'll have a subsection in the NEP I'm writing describing this situation and offering the possible paths forward, hopefully we'll get some feedback from other devs about what the best course of action is.

> I wonder if we could actually realloc or use a chunked scheme to grow the owning buffer during the operation (when there is no way to figure out the length ahead of time). But even that may be hard in practice since a scheme of "allocate empty array and fill it" becomes tricky and.

I don't think it would be too tricky, since we'd always be going through the descriptor.

If it ends up being hard to have a one-to-one mapping from descriptor instances to string storage buffers we could also add a mapping from the descriptor to memory regions owned by that descriptor, but there would still be a unique mapping from descriptors to memory regions outside the array buffer.

Agreed a `finalize` hook could do this too. We could also have an `initialize` hook that lets users bypass the loop inside numpy that calls `setitem` for each array item and instead lets dtype authors implement initialization however they'd wish using a ufunc-like loop over the array buffer. I think having `finalize` and `initialize` hooks might be useful for other dtypes, it's a natural place to put callbacks. Not that I'm excited to implement the hooks immediately...

> It sounds like these allocators try to achieve some memory locality, although if what we want is to operate on the contiguous buffer directly we have lost out: We still need a way to create that "frozenstring" representation.

We want the string data for neighboring array elements to be likely (if not guaranteed) to be located contiguously in memory. Both so that ufunc and casting loops don't page fault on every string access and to eventually enable string SIMD operations.

**Comment by ngoldbaum** [comment]
This is done now using an exponentially expanding buffer for all operations, both for simplicity's sake and because numpy doesn't give us the information we need. (https://github.com/numpy/numpy-user-dtypes/issues/76#issuecomment-1650367922 indicates we do but I was wrong, numpy only does stuff before `__getitem__` is called while doing dtype detection, but stringdtype doesn't participate in dtype detection)

The main uncompleted thing is to resize the arena buffers after the array is filled. This will either require a new dtype API hook in numpy or for numpy to participate in cyclic garbage collection. For the latter option, the dtype could compactify the arena whenever a GC pass touches the dtype instance.
